/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lingex_unsafe_UnsafeObjectModify */

#ifndef _Included_cn_lingex_unsafe_UnsafeObjectModify
#define _Included_cn_lingex_unsafe_UnsafeObjectModify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueInt
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueInt
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueLong
 * Signature: (Ljava/lang/Object;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueLong
  (JNIEnv *, jclass, jobject, jstring, jlong);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueBool
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueBool
  (JNIEnv *, jclass, jobject, jstring, jboolean);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueByte
 * Signature: (Ljava/lang/Object;Ljava/lang/String;B)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueByte
  (JNIEnv *, jclass, jobject, jstring, jbyte);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueShort
 * Signature: (Ljava/lang/Object;Ljava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueShort
  (JNIEnv *, jclass, jobject, jstring, jshort);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueChar
 * Signature: (Ljava/lang/Object;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueChar
  (JNIEnv *, jclass, jobject, jstring, jchar);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueFloat
 * Signature: (Ljava/lang/Object;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueFloat
  (JNIEnv *, jclass, jobject, jstring, jfloat);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueDouble
 * Signature: (Ljava/lang/Object;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueDouble
  (JNIEnv *, jclass, jobject, jstring, jdouble);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectModify
 * Method:    setObjectFieldValueRef
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_lingex_unsafe_UnsafeObjectModify_setObjectFieldValueRef
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
