/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lingex_unsafe_UnsafeObjectRead */

#ifndef _Included_cn_lingex_unsafe_UnsafeObjectRead
#define _Included_cn_lingex_unsafe_UnsafeObjectRead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueBool
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueBool
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueByte
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueByte
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueChar
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueChar
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueShort
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueShort
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueInt
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueInt
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueLong
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueLong
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueFloat
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueFloat
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueDouble
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueDouble
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_lingex_unsafe_UnsafeObjectRead
 * Method:    readObjectFieldValueRef
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cn_lingex_unsafe_UnsafeObjectRead_readObjectFieldValueRef
  (JNIEnv *, jclass, jobject, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
